steps:
  # テストステップ
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python test_markdown_conversion.py
        echo "Tests completed successfully"

  # Cloud Functions デプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy gemini-notion-processor \
          --gen2 \
          --runtime=python312 \
          --region=asia-northeast1 \
          --source=. \
          --entry-point=main \
          --trigger-http \
          --timeout=540s \
          --memory=1Gi \
          --max-instances=10 \
          --allow-unauthenticated \
          --set-env-vars="NOTION_API_KEY=$$NOTION_API_KEY,NOTION_DATABASE_ID=$$NOTION_DATABASE_ID,GEMINI_API_KEY=$$GEMINI_API_KEY,PDF_FILE_PROPERTY_NAME=$$PDF_FILE_PROPERTY_NAME,AUDIO_FILE_PROPERTY_NAME=$$AUDIO_FILE_PROPERTY_NAME,SUMMARY_TOGGLE_H3_TITLE=$$SUMMARY_TOGGLE_H3_TITLE,MEETING_SUMMARY_TOGGLE_H3_TITLE=$$MEETING_SUMMARY_TOGGLE_H3_TITLE,GEMINI_MODEL=$$GEMINI_MODEL"
    secretEnv: 
      - 'NOTION_API_KEY'
      - 'NOTION_DATABASE_ID'
      - 'GEMINI_API_KEY'
      - 'PDF_FILE_PROPERTY_NAME'
      - 'AUDIO_FILE_PROPERTY_NAME'
      - 'SUMMARY_TOGGLE_H3_TITLE'
      - 'MEETING_SUMMARY_TOGGLE_H3_TITLE'
      - 'GEMINI_MODEL'

  # デプロイ後のテスト
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FUNCTION_URL=$(gcloud functions describe gemini-notion-processor --region=asia-northeast1 --format="value(serviceConfig.uri)")
        echo "Function deployed at: $FUNCTION_URL"
        curl -f "$FUNCTION_URL?action=health" || exit 1
        echo "Health check passed"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NOTION_API_KEY/versions/latest
    env: 'NOTION_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/NOTION_DATABASE_ID/versions/latest
    env: 'NOTION_DATABASE_ID'
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/PDF_FILE_PROPERTY_NAME/versions/latest
    env: 'PDF_FILE_PROPERTY_NAME'
  - versionName: projects/$PROJECT_ID/secrets/AUDIO_FILE_PROPERTY_NAME/versions/latest
    env: 'AUDIO_FILE_PROPERTY_NAME'
  - versionName: projects/$PROJECT_ID/secrets/SUMMARY_TOGGLE_H3_TITLE/versions/latest
    env: 'SUMMARY_TOGGLE_H3_TITLE'
  - versionName: projects/$PROJECT_ID/secrets/MEETING_SUMMARY_TOGGLE_H3_TITLE/versions/latest
    env: 'MEETING_SUMMARY_TOGGLE_H3_TITLE'
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_MODEL/versions/latest
    env: 'GEMINI_MODEL'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

timeout: '1200s' 